### ISSUE TITLE
Ability to set arbitrary env vars

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-serve#12]
Right now `ServerFactory::launchServer()` https://github.com/silverstripe/silverstripe-serve/blob/master/code/ServerFactory.php#L37 has the option to set the SERVE_BOOTSTRAP_FILE environment variable.

It would be good to allow arbitrary environment variables to be provided to the server command, that the running SilverStripe site could make use of.

The specific use case I have in mind is for the testsession library. I'd like to pass details of the tmpdb database through to the server process as env vars, and remove any reliance on session variables.

So, something like:

```php
$factory->launchServer([ 'env' => [ 'SS_DATABASE_NAME' : 'tmpdb123453' ]]);
```

I'm not sure if customisable env vars are needed for the CLI script or you can just do those by defining env vars on your CLI call.

I'm planning on raising a PR for this myself, but it's always good to get your feedback. :-)

**Comment by maxime-rainville** [comment]
I've played around a bit. You can pass environment variables to serve via the cli and it seems to work just fine.
```bash
SS_DEFAULT_ADMIN_USERNAME="boom" SS_DEFAULT_ADMIN_PASSWORD="pow" vendor/bin/serve --bootstrap-file vendor/silverstripe/cms/tests/behat/serve-bootstrap.php
```

**Comment by sminnee** [comment]
Yeah I think this ticket predates moving to env vars, so this might be obsolete.
