### ISSUE TITLE
Set unlimited timeout

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-serve#15]
Fatal error: Uncaught exception 'Symfony\Component\Process\Exception\ProcessTimedOutException' with message 'The process "exec /usr/local/Cellar/php56/5.6.29_5/bin/php -S '0.0.0.0:8080' -t '/Users/dmooyman/Sites/ss40test' '/Users/dmooyman/Sites/ss40test/vendor/silverstripe/serve/code/server-handler.php'" exceeded the timeout of 21600 seconds.' in /Users/dmooyman/Sites/ss40test/vendor/symfony/process/Process.php:1265

server dies after 6 hours.

# Relate PR
* [x] https://github.com/silverstripe/silverstripe-serve/pull/23

**Comment by maxime-rainville** [comment]
I think it would just be a question of removing this line.

https://github.com/silverstripe/silverstripe-serve/blob/2eb751606638045488703007d66875bb0e52986f/code/Server.php#L98
